outputSectionTitle("* Data manipulation")
outputString("* Attaching libraries ...")
library(dplyr)
library(tidyr)
library(reshape2) ## Still necessary?
outputDone(step = T)

outputString("Attaching functions ...")
source("fun/renameVar_sxx.R")
source("fun/renameVar_sxx_V2.R")
source("fun/intrpldf_batch.R")
source("fun/intrpldf_batch4rb.R")
source("fun/corrPosAnom.R")
source("fun/corrPosAnom_batch4rb.R")
source("fun/cut2dist.R")
source("fun/cut2dist_batch4rb.R")
source("fun/addVar4PrecVeh.R")
source("fun/addVar4Stopping.R")
source("fun/computeVar_dist2steermax.R")
source("fun/rbindPassings.R")
source("fun/computeSmoothGPSMedian.R")
source("fun/convertGPS2XYDistances.R")
source("fun/computeRadius_batch.R")
source("fun/computeCurvature.R")
source("fun/smoothWithLoess.R")
source("fun/clust2groups.R")
source("fun/clust2groups_hclust.R")
source("fun/clust2groups_kmeans.R")
source("fun/clust2groups_kmeanspp.R")

outputDone(step = T)
