---
title: "Study #2: BFI-10"
#output: github_document
output:
  html_document:
    theme: united
    css: css/faded.css
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Initialise framework
```{r knitr options, include = F}
knitr::opts_knit$set(root.dir='../')
```

```{r Read chunks}
knitr::read_chunk("start_markdown.R")
```

```{r Initialise framework, include = F}
<<start_markdown>>
```

# Analysis

## Preparatory settings

### Connect to database
```{r DB-Connection, message = F}
dbConnectOperator(set4db, dbname = "URBAN-MV-VIE_UniBw_Study2")
```

### Load libaries
```{r Libraries, message = F}
library(psych)
library(ggplot2)
```

### Load data
```{r message = F}
dat_bfi <- dbGetSrc(dbconn_study2, "t_q_bfi10")
head(dat_bfi)
```

## Process data

### Recode items
```{r message = F}
items2recode <- names(dat_bfi)[c(1, 3, 4, 5, 7) + 1]
dat_bfi <- recodeItems(dat_bfi, items2recode, 5)
head(dat_bfi)
```

### Compute scores
```{r messafe = F}
scales2compute <- 
  c("bfi_e", 
    "bfi_n", 
    "bfi_o", 
    "bfi_c", 
    "bfi_a")

items4scales <- 
  list(paste0("bfi", sprintf("%02d", c(1, 6))),
       paste0("bfi", sprintf("%02d", c(4, 9))),
       paste0("bfi", sprintf("%02d", c(5, 10))),
       paste0("bfi", sprintf("%02d", c(3, 8))),
       paste0("bfi", sprintf("%02d", c(2, 7))))

dat_bfi <- 
  computeScores(dat_bfi, 
                scales2compute, 
                items4scales, 
                "mean",
                compZ = T)

head(dat_bfi[, c(scales2compute)])
head(dat_bfi[, c(paste0(scales2compute, ".z"))])
```

## Visualisation and analysis

### Gather data
```{r}
dat_bfi.long <- 
  dat_bfi %>% 
  select(subid, bfi_e:bfi_a) %>% 
  gather(key = subid) %>% 
  setNames(., c("subid", "scale", "score")) %>% 
  mutate(scale = factor(scale, 
                        levels = scales2compute,
                        labels = c("Extraversion",
                                   "Neurotiscm",
                                   "Openness",
                                   "Consiousness",
                                   "Agreeableness")))
```

### Adjust values for plotting points and lines
```{r}
dat_bfi.long$scale.jit <- jitter(as.numeric(dat_bfi.long$scale), factor = 0.4)
dat_bfi.long$score.jit <- jitter(dat_bfi.long$score, factor = 1.5)

head(dat_bfi.long)
```

### Plot boxplot
```{r}
ggplot() + 
  geom_boxplot(data = dat_bfi.long,
               aes(x = scale,
                   y = score,
                   fill = scale),
               alpha = 0.25,
               notch = T, notchwidth = 0.8) +
  geom_point(data = dat_bfi.long,
             aes(x = scale.jit,
                 y = dat_bfi.long$score.jit,
                 colour = scale)) + 
  geom_line(data = dat_bfi.long,
            aes(x = scale.jit,
                y = dat_bfi.long$score.jit,
                group = subid),
            alpha = 0.25) + 
  theme_bw() + 
  ggtitle("BFI-10") + 
  labs(x = "Scale",
       y = "Score",
       fill = "Scale", colour = "Scale")
```

## Correlation
```{r}
pairs.panels(dat_bfi[, scales2compute], 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE # show correlation ellipses
)
```

